### ISSUE TITLE
The shadow under the header does not reach the timeline

### ISSUE THREAD

**Issue by kluverua** [werner-scholtz/kalender#13]
Hi, we really like your calendar!

There is one problem related to UI
If the calendar header(CalendarHeaderBackground) has an elevation (by default it is 2), then its shadow does not reach the left edge of the screen (above timeline bloc)

![image](https://github.com/werner-scholtz/kalender/assets/13339896/52a67bdc-bdd4-40ab-bfec-919aa404c139)

We tried to fix this through the timeline builder.
But without changes in the library, it was not possible. Maybe you will succeed.

Or as a workaround, you can add Divider (with color and height parameters) or some builder here **\kalender\lib\src\views\multi_day_view\multi_day_view.dart:108**

**Comment by werner-scholtz** [comment]
Hi, thanks for bringing it to my attention will have a look at it.

**Comment by werner-scholtz** [comment]
Hi I fixed the issue, the latest version 0.2.0 contains it.

**Comment by kluverua** [comment]
Thank you. But there is still a small problem:
![image](https://github.com/werner-scholtz/kalender/assets/13339896/c0e48193-229a-4792-a4aa-d64ec1e5e856)

**Comment by kluverua** [comment]
Yes, i run \kalender\example\lib\main.dart on android

**Comment by werner-scholtz** [comment]
Hi, should be fixed now let me know if it works for you as well.

**Comment by kluverua** [comment]
Everything looks great!
