### ISSUE TITLE
RFE: ScheduleMonthHeaderBuilder should use internationalized month names

### ISSUE THREAD

**Issue by wstrange** [werner-scholtz/kalender#24]
The month names in ScheduleMonthHeaderBuilder are hard coded ( the month of May is rendered as `Mei` ;-) )

I realize this is a default header builder, but it would be nice if the month names could default to the users locale. Perhaps consider using the `intl` package?

There are probably other places where `intl` could help.

**Comment by werner-scholtz** [comment]
Hi yeah my home language is sneaking into the package ;-).

I most likely add it in the future I just don't have a lot of time right now, you are also welcome to add it yourself if you want.

**Comment by werner-scholtz** [comment]
Hi got around to making the changes you can now pass in a dateFormat String into the DayHeaderStyle, MonthHeaderStyle and ScheduleMonthHeaderStyle.
