### ISSUE TITLE
Bug: Incorrect event duration display and ending day

### ISSUE THREAD

**Issue by chanindev** [werner-scholtz/kalender#25]
Hello, I believe I've identified a minor bug.

In the demo app, when I set a duration of 8 days, the event shows correctly. (Please refer to the screenshot below)
<img src="https://github.com/werner-scholtz/kalender/assets/3127520/77b8b1e2-434a-4740-afd4-7252a6b7ca8f" width = "500"/>

However, when I change the duration to 9 days, the event only shows for 2 days.
<img src="https://github.com/werner-scholtz/kalender/assets/3127520/cb815a9b-e8b1-46c4-be44-034b1361122f" width = "500"/>

Additionally, the bug occurs when I set the duration to end on Sunday.

Thank you.

**Comment by werner-scholtz** [comment]
Hi thank you for finding it and letting me know, it should be fixed in the latest release v0.2.3.

**Comment by chanindev** [comment]
Thanks for fixing it :)
