### ISSUE TITLE
Date range issue

### ISSUE THREAD

**Issue by NobleO11** [werner-scholtz/kalender#27]
Hello, 

thank you for your hard work.

I just noticed there is a bug regarding the date range fields in the new & edit events popup. when trying for example to add new event, then if clicked on the date (From or To ), then choose any date and click ok, now the chosen date is no appearing or not reflexed. 

note this is a UI thing only, even if the new chosen date is not showing but when clicked on save, the new event will be created correctly with the dates chosen by user.

**Comment by werner-scholtz** [comment]
Thanks for letting me know, it should be fixed now :D

**Comment by NobleO11** [comment]
thank you so much for your efforts :)
