### ISSUE TITLE
customizing the tiles

### ISSUE THREAD

**Issue by kayatmin** [werner-scholtz/kalender#29]
Hi, is there a way to customize the tiles? not the event tiles, but just the regular tiles in the calendar.

i'd like to make tiles that are past from DateTime.now show in disabled shaded color.

**Comment by werner-scholtz** [comment]
I'm not really sure what you mean, maybe a image could help. From what I understand you want to change the background color of the days that are in the past. This goes for the MultiDayView and MonthView.

**Comment by kayatmin** [comment]
@werner-scholtz thanks for the quick reply!

i'd like to achieve something like the following:

![image](https://github.com/werner-scholtz/kalender/assets/7703058/c3528419-6fcf-4abe-9503-085c96ec252d)

where the dark bordered tiles are in the past and shaded with grey strips.. preferably also able to disable the click events for these tiles.

**Comment by werner-scholtz** [comment]
Aaah okay, I take it you also don't want those area's to allow the user to create events ?

**Comment by kayatmin** [comment]
yes you're right. i could achieve the behavior by checking the current time against the time range given by the event handler on clicks, however i need a way to make those tiles in the past look different.

**Comment by werner-scholtz** [comment]
To achieve the background I recommend you create a custom hourLineBuilder that can draw the background where you need it ([hourlines](https://github.com/werner-scholtz/kalender/blob/c4c77d703c9f2744f4eed8006d880abde87657a0/lib/src/components/general/hour_line/hour_lines.dart#L6)), you can take a look at how the [time-indicator](https://github.com/werner-scholtz/kalender/blob/c4c77d703c9f2744f4eed8006d880abde87657a0/lib/src/components/general/time_indicator/time_indicator.dart#L8) works for some inspiration.

**Comment by kayatmin** [comment]
ok, thank you! will dive in deeper.

**Comment by werner-scholtz** [comment]
Cool let me know if you succeed :+1:

**Comment by werner-scholtz** [comment]
Hi I was thinking this might be a good example to add to the package, would you be able to do it ?
