### ISSUE TITLE
Repeatable Events

### ISSUE THREAD

**Issue by Huber1** [werner-scholtz/kalender#36]
Hello Werner,
Thanks for your awesome work with this package!

If possible, could you please implement a functionality to repeat an event?

I'm currently implementing a calendar view into an app for my university (University of Applied Sciences Munich).
Since the lectures repeat every week, it would be great to display them in the calendar without the need to split the event into multiple.

Thanks in advance,
Moritz

**Comment by werner-scholtz** [comment]
Hi, that is unfortunately not something that I will be implementing anytime soon, so for now you would need to create multiple CalendarEvent entries if you want repeating events. You should be able to leverage the Custom Object passed into CalendarEvent to reschedule the repeating events.

**Comment by Huber1** [comment]
Fine. I think I'll have to split the events then 🙂.
Thanks for the awesome work on the package!
