### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by MarlonPra** [werner-scholtz/kalender#38]
Hello, I am studying software engineering in Colombia and I need to use this package for my project which is about the creation of schedules for a university, my question is if there is any translation into Spanish?

**Comment by werner-scholtz** [comment]
Hi this package does not support other languages yet, however you should be able to customise all text displayed by the calendar  to spanish.

**Comment by werner-scholtz** [comment]
I will look into localising the package, I am quite busy atm so it might take a while.

**Comment by MarlonPra** [comment]
> I will look into localising the package, I am quite busy atm so it might take a while.

Ohh, okey no problem relax 😎

**Comment by werner-scholtz** [comment]
Linked to this #38 
Planned to do this very soon.
