### ISSUE TITLE
Can the start and end hours of a DayCalendar be set?

### ISSUE THREAD

**Issue by davoutuk** [werner-scholtz/kalender#4]
I see that by default the day calendar shows all hours of the day.

Instead,  I am looking to just show the hours between 8am and 8pm.    Can I do this with this widget?

**Comment by werner-scholtz** [comment]
Hi, that is not yet implemented but it is definitely something I will implement.

**Comment by werner-scholtz** [comment]
Hi, it has been implemented you can give it a try.

**Comment by naabin** [comment]
Hi werner, I am using `kalender: ^0.1.8` and  still I cannot set `start` and `end` hours as explained in the readme.doc in the `ViewConfiguration` section

**Comment by werner-scholtz** [comment]
Hi Sorry about that it should be fixed now with v0.1.9
