### ISSUE TITLE
Drag & Drop 'CalendarEvent' from outside the 'CalendarView'

### ISSUE THREAD

**Issue by aa-adibashraf** [werner-scholtz/kalender#48]
Hi, I was wondering if there's a way to drag & drop a CalendarEvent object which is not currently in the CalendarView's event controller into the CalendarView. I've checked that the MultiDayView/Content do not use DragTarget so I was trying to select the event and set isRescheduling to true while dragging but can't seem to properly determine the new DateTimeRange. 
Any help would be appreciated!

**Comment by werner-scholtz** [comment]
Interesting way to use the package, I will investigate how to implement this. As I am short on time it might take a while.

**Comment by aa-adibashraf** [comment]
Please take your time, no rush. This is already an amazing package with a lot of depth.

**Comment by werner-scholtz** [comment]
H, just an update I'm in the slow process of rewriting parts of the package to make it more configurable and flexible and I will definitely be adding this feature to the package.

**Comment by aa-adibashraf** [comment]
Thank you for the update! Looking forward to it.

**Comment by werner-scholtz** [comment]
Hi just an update, I have started work on this see calendar_rework branch the calendar is now using a DropTarget so it should be possible to drop CalendarEvent in the calendar view, It is slow progress because I have been very busy recently.

**Comment by aa-adibashraf** [comment]
That's completely fine, take your time with it.
