### ISSUE TITLE
how to show multi day events in calendar grid?

### ISSUE THREAD

**Issue by Shui-Be** [werner-scholtz/kalender#49]
Hi Thank you for the awesome package!

I was wondering if it's possible to show full day events in the calendar grid instead of calendar header area.

for instance, i have an event that lasts from `2024-April-21` to `2024-April-23`, i would like to show it as three columns in the calendar grid.

something like this:

![image](https://github.com/werner-scholtz/kalender/assets/167668764/403f3235-18c6-4601-95db-a8646d138648)

i've tried passing in the flag `createMultiDayEvents: false,`, it did make the multi-days events in the calendar header area disappear, but it doesn't show in the grid...

hoping if you could pls point me to the right direction in code, and if you could provide some guidance on what i can do for custom implementation that would be greatly appreciated!

**Comment by werner-scholtz** [comment]
Hi that is not possible yet, it should be straight forward and quick to implement so I will provably be able to do soon that since there is already a parameter that hides the `day header` I just need to force the events in the header to be rendered in the grid if that is set to false.

**Comment by werner-scholtz** [comment]
Okay so yeah tried it seems like there are some bugs with displaying events that span multiple days in the grid view which I will need to fix first.

**Comment by werner-scholtz** [comment]
You can try the latest changes https://werner-scholtz.github.io/kalender/

**Comment by Shui-Be** [comment]
thank you for the super quick response!

the latest version worked very well:
![image](https://github.com/werner-scholtz/kalender/assets/167668764/43af6437-952c-4d27-a4f8-94f3c6f37d2b)
