### ISSUE TITLE
missing language localizzation for days of the week in header and showDayHeader don't work

### ISSUE THREAD

**Issue by GSFdev24** [werner-scholtz/kalender#60]
Hello team,

i see that in components **DayHeaderStyle** and **MonthHeaderStyle** there is the possibility to change the date format of day of the week, but i don't see the possibility to change the language localization and the days of the week are only in english.

In the next release will there be the possibility to change the language? Or it's already there and I didn't notice it, in which case I apologize for opening a useless issue.

in add i notice that the **showDayHeader**  that which it replaced **showHeader** in **CustomMultiDayConfiguration**  doesn't work 

Best Regards and thank for your work.

**Comment by werner-scholtz** [comment]
Hi yeah sure I see intl package has a way to set the locale it is just not exposed, I'll change it in the next version for now you can use the monthHeaderBuilder and dayHeaderBuilder to customize the langauge used.

**Comment by GSFdev24** [comment]
> monthHeaderBuilder

ok thank you i will wait your next release and instead why showDayHeader  doesn't work such as showHeader ? Am I doing something wrong?

**Comment by werner-scholtz** [comment]
> Hello team,
> 
> i see that in components **DayHeaderStyle** and **MonthHeaderStyle** there is the possibility to change the date format of day of the week, but i don't see the possibility to change the language localization and the days of the week are only in english.
> 
> In the next release will there be the possibility to change the language? Or it's already there and I didn't notice it, in which case I apologize for opening a useless issue.
> 
> in add i notice that the **showDayHeader** that which it replaced **showHeader** in **CustomMultiDayConfiguration** doesn't work
> 
> Best Regards and thank for your work.

I also had another look at the localisation what I'm going to do is remove the intl package from the calendar package and just have a string builder in the style classes that way you can use the intl to decide what to display.
