### ISSUE TITLE
Question: time issue

### ISSUE THREAD

**Issue by NobleO11** [werner-scholtz/kalender#62]
Hello, thank you for your awesome package.

I'm using your awesome package, and it is fantastic, however there is issue about time and did not manage to fix it.

the issue is: when retrieving events from backend everything is good except for the time will be subtracted by 3 hours. 
for example. if I create event [start date: 25/4/2024 10:00:00, end date: 26/4/2024 11:00:00] it will be created and stored to database perfectly and correctly. but when retrieve it will be subtracting 3 hours so will be like [start date: 25/4/2024 07:00:00, end date: 26/4/2024 08:00:00]. I tried to find the issue by debugging but everything is good except when the process enters the package. I knew the issue is in the package but could not know where exactly.

another example: when create event at day 20 time 00:00:00 it will become the previous day at day19 and time at 21:00:00, and this is big problem for me.

so, any UTC issues or anything that may cause this you think or anything that may help me fix this?

**Comment by werner-scholtz** [comment]
So when you create a event with the Calendar ex:
`start: 25/4/2024 10:00:00, end: 26/4/2024 11:00:00` it gets stored in the database correctly but when you fetch the data from the database and give it to the Calendar it moves it back 3 hours ?

**Comment by werner-scholtz** [comment]
When you create the CalendarEvent you need to pass in a dateTimeRange:
```
CalendarEvent<Event>(
  dateTimeRange: dateTimeRange,
;
```
can you check if the dateTimeRange you pass in is in local time or utc time ?

**Comment by NobleO11** [comment]
toLocal() solved my issue big thank you :).
