### ISSUE TITLE
Custom vertical scroll controller

### ISSUE THREAD

**Issue by aditzer** [werner-scholtz/kalender#63]
Hello Werner,

I have been using your package for a while and I have a question for you. I want to provide a vertical scrollController myself to the Calendar widget. Is there any way to do so, if not then how can I achieve it by modifying current package code?

**Comment by werner-scholtz** [comment]
Hi, so this isn't possible currently so you would need to make changes to the package, however if you are not in a rush I'm in the process of slowly rewriting parts of the package that would make things like this possible.

Just some notes only the MultiDayView uses a scroll controller, the schedule view uses a ItemScrollController from the [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list) pacakge.

To use your own `ScrollController`
1. Pass in a `ScrollController` to the [CalendarView](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/views/calendar_view.dart#L115)
2. Pass it into the [MultiDayView](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/views/multi_day_view/multi_day_view.dart#L20)
3. Pass it into the [attach](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/calendar/calendar_controller.dart#L86) function called [here](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/views/multi_day_view/multi_day_view.dart#L117)
```
I would recommend to make it nullable and not required,
as this function is called from all the different views which do not necessarily have scrollControllers.

ViewState? attach(ViewConfiguration viewConfiguration, {ScrollController? Scrollcontroller}) {...}
```
5. Pass it into the [MultiDayViewState.fromViewConfiguration](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/calendar/view_state/multi_day_view_state.dart#L25) called [here](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/calendar/calendar_controller.dart#L93)
6. And use it [here](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/calendar/view_state/multi_day_view_state.dart#L67)
