### ISSUE TITLE
Dragging across weeks & general suggestions

### ISSUE THREAD

**Issue by marcoancona** [werner-scholtz/kalender#64]
Thanks for building this amazing library, which is already one of the best Flutter calendars out there. 

One of the UX requirements for us would be to be able to drag & drop events across weeks, i.e. long tap to start dragging an event, move it towards the edge of the screen to trigger the scroll to another week, and continue dragging to set a new date and time. See a demo of what I mean on another  app here: https://share.cleanshot.com/blx5fkSz

We tried to play with the library internally to achieve this, but it is currently tricky cause the event is a child of the current page being displayed. 

Would it make sense to have the widget being dragged rendered at the root level of the widget tree instead, for more flexibility? This would allow the draggable widget to move freely on the user's finger, also across pages. Like in the video I posted above, a placeholder could be used to indicate where the event is going to drop.

I am posting this idea since you mentioned you are considering some refactoring as part of https://github.com/werner-scholtz/kalender/issues/48 (which, by the way, is also something we'd love to see).

**Comment by werner-scholtz** [comment]
I agree this would be a very nice feature to add. I would have to investigate how to accomplish this since as you said the tile is a child of the current page.

**Comment by werner-scholtz** [comment]
Hi here is a short clip showing the current progress, not 100% ready yet but it is slowly getting there
[Screencast from 17-05-2024 07:29:20.webm](https://github.com/werner-scholtz/kalender/assets/121276491/733418db-978f-4055-90c8-e45951f35107)

**Comment by marcoancona** [comment]
> Hi here is a short clip showing the current progress, not 100% ready yet but it is slowly getting there [Screencast from 17-05-2024 07:29:20.webm](https://github.com/werner-scholtz/kalender/assets/121276491/733418db-978f-4055-90c8-e45951f35107)

Looks great! Looking forward to try it!
