### ISSUE TITLE
Tile does not appear on the last day

### ISSUE THREAD

**Issue by NobleO11** [werner-scholtz/kalender#65]
Hello, I see that the tile is not being drawed to the last day, any idea how to accomplish this without increasing the toDate value?

when for example set fromDate = "2024-04-09 05:00:00.000" and toDate = "2024-04-10 04:01:00.000", as you can see this event is on 2 days, but it will draw tile on the "2024-04-09 05:00:00.000" only, because this event's duration is less than 24 hours, if it is more than 24 hours it will draw tiles correctly to the end. so, I can increase the toDate until it is more than 24 hours ahead from fromDate but it is not recommended since info here must be very accurate and must not change anything. because I'm using it for real events for public.

note: I can't change user input to manipulate tiles because then there is no accuracy.

if you could look into this matter, it will be appreciated, thank you.

**Comment by werner-scholtz** [comment]
Hi I'm not sure what you mean exactly so when I input this fromDate = "2024-04-09 05:00:00.000" and toDate = "2024-04-10 04:01:00.000" it renders the tile on both days, is this not the case for you ?

![image](https://github.com/werner-scholtz/kalender/assets/121276491/54248541-b2a6-48e6-9841-1d318b9c5e16)

**Comment by NobleO11** [comment]
I mean in Month view. 

![Screenshot (4)](https://github.com/werner-scholtz/kalender/assets/78362115/5949e99a-bb7a-4543-9383-1397e965adb4)

check above image, the tile is not rendered in the last day. 

![Screenshot (5)](https://github.com/werner-scholtz/kalender/assets/78362115/4ce5aeb4-a875-44fb-b03d-40ecee98487b)

and now check this, it is rendered now because the toDate time [I mean only hour & minutes] is more than the fromDate.

both screenshots as you can see is on same days but different in hours

**Comment by werner-scholtz** [comment]
Will fix, thanks for finding the bug 👍

**Comment by werner-scholtz** [comment]
Hi I have the fixed lined up, it is applied to the web_demo just give it a try there and let me know if it fixes the issue for you. then I will merge the pr.

**Comment by NobleO11** [comment]
thank you so much. it is good now :).
