### ISSUE TITLE
Click and Drag in Weekview has offset when start or end hours are changed

### ISSUE THREAD

**Issue by enwi** [werner-scholtz/kalender#67]
When creating a new event in the week view by clicking and dragging the position is offset when the start or end hours have been changed.

Here is an example where I have changed the start hour to `4:00`and end hour to `20:00`:
![chrome-capture-2024-4-29](https://github.com/werner-scholtz/kalender/assets/25170066/46081995-0b64-4987-93c9-db3661309be1)

**Comment by werner-scholtz** [comment]
Hi thanks will look into that.

**Comment by enwi** [comment]
There is actually another bug, which allows you to create an event past the end hour that is probably related to this

**Comment by enwi** [comment]
I hope it is an easy fix and thanks for your awesome work 🙂
