### ISSUE TITLE
CustomMultiDayConfiguration haven't the property showHeader like MonthConfiguration

### ISSUE THREAD

**Issue by GSFdev24** [werner-scholtz/kalender#68]
Hello team ,

i see that in the last release was added for MonthConfiguration the boolean property showHeader that hide or show the header for month view;

Is possible introduce this feature for  CustomMultiDayConfiguration  with the property number of days set to 1?

i remember that for the old version this property is present also for CustomMultiDayConfiguration  

Thank you a lot for your work

Regards

**Comment by werner-scholtz** [comment]
Hi this already exists there are two parameters here:
[_showDayHeader / showDayHeader](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/view_configurations/multi_day_configurations/multi_day_view_configuration.dart#L253)
and 
[_showMultiDayHeader / showMultiDayHeader](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/view_configurations/multi_day_configurations/multi_day_view_configuration.dart#L262)

**Comment by GSFdev24** [comment]
> Hi this already exists there are two parameters here: [_showDayHeader / showDayHeader](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/view_configurations/multi_day_configurations/multi_day_view_configuration.dart#L253) and [_showMultiDayHeader / showMultiDayHeader](https://github.com/werner-scholtz/kalender/blob/00cd7fd88d70acacf0c81581a6354e9515e6bbb0/lib/src/models/view_configurations/multi_day_configurations/multi_day_view_configuration.dart#L262)

Ok , but if in CustomMultiDayConfiguration   set the property showDayHeader to false the Headerof calendar is not hidden

**Comment by werner-scholtz** [comment]
I believe that the showHeader in the monthView does not hide the "calendarHeader" it just hides the day names.

**Comment by werner-scholtz** [comment]
Oh I see what you mean the weekNumber/dayNumber is still shown even if you hide the header. will fix.

**Comment by GSFdev24** [comment]
> Oh I see what you mean the weekNumber/dayNumber is still shown even if you hide the header. will fix.

yes i am sorry not the header but yes the day number
