### ISSUE TITLE
Timezone bug

### ISSUE THREAD

**Issue by aditzer** [werner-scholtz/kalender#69]
In few timezones (Romanian for example) this is happening:

1. I created an event on 29th by tapping, event date is created as 28th.
2. When I created an event by code for 29th, the event gets mapped to 30th.

If you know this bug, how can it be solved?

<img width="287" alt="Screenshot 2024-04-30 at 1 30 10 AM" src="https://github.com/werner-scholtz/kalender/assets/53402554/311dcd08-a8d6-4bb7-b88d-01700e179731">

**Comment by werner-scholtz** [comment]
Maybe take a look at issue #62 seems like a similar issue, if it does not solve the issue let me know.

**Comment by aditzer** [comment]
Hey, I am already passing everything in Local format, so that does not work either

**Comment by werner-scholtz** [comment]
I'm struggling to replicate that with the web demo (Changed my timezone to EEST), can you also check if you can replicate the bug with the web demo https://werner-scholtz.github.io/kalender/ ? Also are you using the latest version of the package ?
