### ISSUE TITLE
Opportunity to set width for events

### ISSUE THREAD

**Issue by GSFdev24** [werner-scholtz/kalender#70]
Hello team,

i want ask you if there is the opportunity to set the width of the event when i add it on calendar, because in my case when there are many events in the same day  ,I would prefer to view them next to each other and not one below the other because  the first event that occupies all available width.

I always thank you for the work you do 

Regards

**Comment by werner-scholtz** [comment]
Hi do you means something like this ? 
![image](https://github.com/werner-scholtz/kalender/assets/121276491/aee5f139-bd1f-4dd9-9a23-955d1a88b5ad)

**Comment by GSFdev24** [comment]
> Hi do you means something like this ? ![image](https://private-user-images.githubusercontent.com/121276491/327101803-aee5f139-bd1f-4dd9-9a23-955d1a88b5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1ODM5NDQsIm5iZiI6MTcxNDU4MzY0NCwicGF0aCI6Ii8xMjEyNzY0OTEvMzI3MTAxODAzLWFlZTVmMTM5LWJkMWYtNGRkOS05YTIzLTk1NWQxYTg4YjVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxNzE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzNjMjM1MGZiYWNiMGI0M2VkOWZjOWJmOTcwNDk3ZGU3MWU5ZTYxNWIwYmVlNzkzZWViNTYyMGRmMzkxNTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TLhLFN8LuHPdGSS7ygSvOr_hr2HlXFu3bc9bfqSKIvU)

yes, the example of events 612,610,611 under saturday 4 is perfect

**Comment by werner-scholtz** [comment]
You can use the EventGroupBasicLayoutDelegate for this 
```
    CalendarWidget(
      calendarLayoutDelegates: CalendarLayoutDelegates(
        tileLayoutDelegate: ({
          required date,
          required endHour,
          required events,
          required heightPerMinute,
          required startHour,
        }) {
          return EventGroupBasicLayoutDelegate<Event>(
            events: events,
            date: date,
            heightPerMinute: heightPerMinute,
            startHour: startHour,
            endHour: endHour,
          );
        },
      ),
    );
```

**Comment by GSFdev24** [comment]
> You can use the EventGroupBasicLayoutDelegate for this
> 
> ```
>     CalendarWidget(
>       calendarLayoutDelegates: CalendarLayoutDelegates(
>         tileLayoutDelegate: ({
>           required date,
>           required endHour,
>           required events,
>           required heightPerMinute,
>           required startHour,
>         }) {
>           return EventGroupBasicLayoutDelegate<Event>(
>             events: events,
>             date: date,
>             heightPerMinute: heightPerMinute,
>             startHour: startHour,
>             endHour: endHour,
>           );
>         },
>       ),
>     );
> ```

Ok, Great it works perfectly, thanks
