### ISSUE TITLE
bug: not showing the current day.

### ISSUE THREAD

**Issue by NobleO11** [werner-scholtz/kalender#71]
hello, in the month view some times the calendar widget doesn't recognize the current date to show by default. 

for example check below video: 

https://github.com/werner-scholtz/kalender/assets/78362115/21429920-d21d-42d4-b9a3-5bca97309419

current day is second of may, yet it is not included in the current visible dateRange as you can see.

note: if the firstDayOfWeek is monday it may be good but other days are causing this type of bug.

thanks

**Comment by NobleO11** [comment]
I want to add also in my case. I have the calendar widget and beside it in the same page is list of events. when clicked on any event it animates to the event's date correctly in general except for this bug. if I have a event on second of may for example and i clicked on it, it will animate the page to the wrong page the exact same as in video above. so this but is not in all months or it is not always occurring, but in the current month (may) it is causing a lot of problems.

**Comment by werner-scholtz** [comment]
Hi thanks will see if I can figure out what is going wrong.

**Comment by UsamaKarim** [comment]
Is the visible month date hardcoded? I see April as the first month.
<img width="465" alt="Screenshot 2024-05-03 at 1 13 45 AM" src="https://github.com/werner-scholtz/kalender/assets/64292174/1f3058bc-b0cf-458b-ad4d-ceb8552b4d6a">

**Comment by werner-scholtz** [comment]
> Is the visible month date hardcoded? I see April as the first month. <img alt="Screenshot 2024-05-03 at 1 13 45 AM" width="465" src="https://private-user-images.githubusercontent.com/64292174/327575047-1f3058bc-b0cf-458b-ad4d-ceb8552b4d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjQ0NzIsIm5iZiI6MTcxNDcyNDE3MiwicGF0aCI6Ii82NDI5MjE3NC8zMjc1NzUwNDctMWYzMDU4YmMtYjBjZi00NThiLWFkNGQtY2ViODU1MmI0ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA4MTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZWJhMGUxYzFhMGVlYjJhM2JiMzZkYjg3OGVlZjJlMjQ5OWQwNzZiNjRjZDQ2NDZkMzBiMDRjNmZhMWI1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rudbqvpgtn6sjDRmdkIRSP5T4-rogtsVrIwhz2l2JMY">

I found the issue the visibleMonth from the CalendarController was returning the incorrect value,
