### ISSUE TITLE
Change the color and font of day in weekly configuration

### ISSUE THREAD

**Issue by GSFdev24** [werner-scholtz/kalender#74]
Hi Team ,

for the weekly configuration I haven't found any way, to change the color and the font of number of day in header, but only the name of the week changes.

I attach a photo to explain my problem better, in the red circles you can see the numbers of the day whose color and font I cannot change

<img width="921" alt="calendar" src="https://github.com/werner-scholtz/kalender/assets/13691918/c48d09fb-6679-4f10-aff5-3c900fef098f">

thank you a lot for your work
Regards

**Comment by werner-scholtz** [comment]
Hi you should be able to pass in a custom builder for [that](https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/models/calendar/calendar_components.dart#L46)

**Comment by werner-scholtz** [comment]
I am currently in the process of rewriting the package so I will add a stringbuilder and textstyle in the new version of the package.

**Comment by GSFdev24** [comment]
> Hi you should be able to pass in a custom builder for [that](https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/models/calendar/calendar_components.dart#L46)


i customize the components dayHeaderBuild and now i have this result:
<img width="923" alt="calendario2" src="https://github.com/werner-scholtz/kalender/assets/13691918/f7b4c530-1c99-45d0-a6f3-c6be9fae164c">

thanks a lot for the tip

**Comment by werner-scholtz** [comment]
Glad I could help
