### ISSUE TITLE
Auto-scroll when dragging events

### ISSUE THREAD

**Issue by aa-adibashraf** [werner-scholtz/kalender#75]
Hi, it would be very helpful if there was an option to enable auto-scrolling when dragging events close to the edge of the page. Enabling support for custom ScrollControllers would also help in achieving this.

**Comment by werner-scholtz** [comment]
Hi yes it is in the works, currently on the calendar_rework branch

**Comment by werner-scholtz** [comment]
Short clip of the progress
[Screencast from 17-05-2024 07:29:20.webm](https://github.com/werner-scholtz/kalender/assets/121276491/4aa58d22-070b-417e-9a0e-cf05f3c34622)

**Comment by aa-adibashraf** [comment]
Looks like it's coming along really well!
I see you're also dragging & dropping from another widget. Does this also mean that the feature to drag & drop a 'CalendarEvent' from a non CalendarView is implemented?

**Comment by werner-scholtz** [comment]
Yes it is implemented :D

**Comment by aa-adibashraf** [comment]
Amazing! Can't wait to try it out.
