### ISSUE TITLE
Question: While Developing, Reload Package changes?

### ISSUE THREAD

**Issue by ronnyek** [werner-scholtz/kalender#77]
Sorry this is more of a question of actually attempting to fix bugs (adding features) for PR. I'm curious if I clone this solution and use the example folder as the sort of container project to visualize changes, should I be able to see updates to the package rendered within the example app? Is there something I need to Enable?

I noticed the example project is just referencing Kalender library as if it was a relative import (up a folder structure). I dont even know of a way to build the Kalendar package such that I can import the changes into the example app, as flutter/dart cli tools seem to want to spit out a new executable (mobile/web/windows).

So far I opened the Kalendar project, and then just have a debug configuration that just starts `./example` project.

**Comment by werner-scholtz** [comment]
Hi, yes it is setup so that when you make changes in the package `lib/..` it will reflect in the example app.

You can start the example app with:
1. `cd example && flutter run`
2. Using VS code's run and debug tab.

You can then make changes in the package `lib/...` and use hot reload to reflect those changes.

* just a note I'm currently working on the calendar_rework branch which might fix a lot of the current issues, it is a rewrite basically but it is still a while before it will be done.

**Comment by ronnyek** [comment]
well one of the reasons I was looking into this, is I'd actually like to specifically use it with fluentui without the material ui stuff. I have that part working, but some of the styles are not correct.

**Comment by werner-scholtz** [comment]
Hi, I don't have experience working with fluent ui, so if you don't mind can you let me know which parts are not working for you.

The best solution I see for this is to allow overrides for all the UI widgets in the package.

**Comment by ronnyek** [comment]
Essentially fluentui replaces the sources of a lot of types. They keep the same name in a lot of cases, but come from fluentui packages. Most of the styles are not there as well. I'm not sure how worth making the UI framework pluggable would be (I suspect it would be unnecessary for your needs...)

**Comment by werner-scholtz** [comment]
I see, yeah not really worth it for me. However you should be able to override all the default widgets to use custom ones that use fluentui quite a bit of work though.
