### ISSUE TITLE
Custom Hour Height 

### ISSUE THREAD

**Issue by Barry0501** [werner-scholtz/kalender#80]
Hello author, thanks for taking the time to create a great library. Because the Event has a duration of 15 minutes displayed in the interface is too small, I want to extend the hourly interval to display full event information with a duration of 15 minutes. How can I do that?

<img width="130" alt="Screenshot 2024-07-04 at 16 18 04" src="https://github.com/werner-scholtz/kalender/assets/34902237/ffd2d69b-5f1d-4f66-9d46-d0c383d88b2f">

**Comment by werner-scholtz** [comment]
Hi you should be able to adjust the heightPerMinute value on the calendar controller, which increases the hourly interval.
The [web_demo](https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/other_examples/web_demo/lib/main.dart#L103) has an example of how to use [cntl+scroll wheel](https://github.com/werner-scholtz/kalender/blob/main/other_examples/web_demo/lib/widgets/calendar/calendar_zoom.dart) to zoom in/out on the calendar, this also works with pinch to zoom on mobile.

**Comment by KmiloRe** [comment]
Hi, could you please clarify where should I change the heightPerMinute exactly on the calendar view in order to make the hourly interval bigger? sorry to bother you, thanks 4 the great library!

**Comment by werner-scholtz** [comment]
Hi yeah, the CalendarController has a function [adjustHeightPerMinute(double value)](https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/models/calendar/calendar_controller.dart#L223) which you can use to change the height.

**Comment by x-ji** [comment]
This seems to have been changed after 0.5.0. I looked around and found out that this is an argument to the `viewConfiguration` called `initialHeightPerMinute`, with a default value of `0.7`. Example:

```
CalendarView(
  // other arguments
  viewConfiguration: MultiDayViewConfiguration.singleDay(initialHeightPerMinute: 1.4)
)
```
