### ISSUE TITLE
Issue in week days header

### ISSUE THREAD

**Issue by laguerreuy** [werner-scholtz/kalender#81]
![Screenshot_20240707_155529](https://github.com/werner-scholtz/kalender/assets/83300557/a9cf9e5c-b396-46a9-be7f-af62a3c0a7eb)

The days headers should be all equal in width. In my specific case I use a different content for Mondays and it causes a disalignment on narrow screens.

**Comment by werner-scholtz** [comment]
Hi, thanks for the issue. Will take a loo.

**Comment by werner-scholtz** [comment]
Hi v0.5.0 has been released, the DayHeader's are now constrained so you should get a layout error if they do not conform.
