### ISSUE TITLE
Getting issue in Editing Events

### ISSUE THREAD

**Issue by AniketStemmOne** [werner-scholtz/kalender#82]
If there are multiple events on single day, 
if we edit any of it the first event will be also be updated by same value 

how to fix it ??

  eventController.updateEvent(
                                          modifiable: true,
                                           newDateTimeRange: DateTimeRange(
                                           start: task.startDate!,
                                              end: task.endDate!),
                                          newEventData: task,
                                          test: (calendarEvent) {
                                            return true;
                                          },
                                        );
                                        
                                        its is always updating first event also

**Comment by werner-scholtz** [comment]
Hi, so in the code you provided the `test` always returns `true` which means it will update the first event. [see this for how the updateEvent works](https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/models/calendar/calendar_event_controller.dart#L117) 

You should have the test function return true for the event you want to update, 
ex. You want to update the event where the EventData matches `someEvent`.
```dart
eventController.updateEvent(
  modifiable: true,
  newDateTimeRange: DateTimeRange(
  start: task.startDate!,
  end: task.endDate!),
  newEventData: task,
  test: (calendarEvent) {
    return calendarEvent.eventData == someEvent.eventData;
  },
);
```
