### ISSUE TITLE
Scrolling with trackpad causes an event to be created

### ISSUE THREAD

**Issue by Levi-Lesches** [werner-scholtz/kalender#84]
Here's how we can fix it: 
- add a check for `details.kind == PointerDeviceKind.trackpad` here, then return out of the function:
https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/components/gesture_detectors/multi_day_page_gesture_detector.dart#L126-L130
- instead of stacking the gesture detector over the calendar, add it as a child here: 
https://github.com/werner-scholtz/kalender/blob/50043322a49ade38194ae9c477c5691bcb697294/lib/src/views/multi_day_view/multi_day_page_content.dart#L169-L177

That should let trackpads scroll the calendar view

**Comment by BagaudinP** [comment]
`final gestureDetector = GestureDetector(
              onLongPress: () => longPress ? _createNewEvent(date, index) : controller.deselectEvent(),
              onTap: () => tap ? _createNewEvent(date, index) : controller.deselectEvent(),
              onVerticalDragStart:
                  isMobileDevice || !createEvents ? null : (details) => _onVerticalDragStart(details, date, index),
              onVerticalDragUpdate:
                  isMobileDevice || !createEvents ? null : (details) => _onVerticalDragUpdate(details, date, index),
              onVerticalDragEnd: isMobileDevice || !createEvents ? null : _onVerticalDragEnd,
              supportedDevices: const <PointerDeviceKind>{
                PointerDeviceKind.touch,
                PointerDeviceKind.mouse,
              },
            );`
there is an easier way, add supportedDevices for GestureDetector
