### ISSUE TITLE
Question about visible date range

### ISSUE THREAD

**Issue by NobleO11** [werner-scholtz/kalender#85]
Hi @werner-scholtz ,

quick question: is there notifiers or something that return the new visible month when (animateToPrevousPage, animateToEvent, animateToDate etc..) 

as mi showing a list of events I want to show the list of the visible events only (events for current shown month), not all events. I tried calendarController.visibleMonth but it returns null.

thank you for your efforts :)

**Comment by werner-scholtz** [comment]
Hi @NobleO11 ,

Not 100% sure why that is returning null in your case, are you using a month configuration in the calendar view ?

In the new version of the kalendar package there will be two notifiers that you can use for something like this.
1. `ValueNotifier<DateTimeRange> visibleDateTimeRange` (The current visible date time range.)
2. `ValueNotifier<List<CalendarEvent<T>>> visibleEvents` (The current visible events.)

**Comment by NobleO11** [comment]
no problem I did a workaround, and it is working now.

and I don't know why it returns null. I'm using the month and week view configurations. 

maybe it returned null because I'm trying to access it from mian.dart (outside of the calendarWidget class) ?

thank you i will wait for the next release, do you know when it will come out?

**Comment by werner-scholtz** [comment]
Hi, a early version will be available by the end of the month. 
The full release to pub.dev might take a bit longer as I want to find and fix as many bugs as possible first.

**Comment by werner-scholtz** [comment]
Hi v0.5.0 has been released and the `visibleDateTimeRange` and `visibleEvents` should now be working correctly.
