### ISSUE TITLE
Kalendar Rework SoW

### ISSUE THREAD

**Issue by mosabalrsaheed** [werner-scholtz/kalender#87]
Hi @werner-scholtz , 

Awesome work here, really like the library and I see great potential. 
Was just asking about the scope of work, motivation and any open issues I can contribute to in the rework.
I have checked the project tab but it seems it's not updated kinda.

Thanks

**Comment by werner-scholtz** [comment]
Hi @mosabalrsaheed 

Thank you.
I needed a free calendar package that could do drag and drop for an internal app, I initially used https://pub.dev/packages/calendar_view and event tried adding drag and drop to it but it was very hacky and didn't work well. So I created this package as a solution to that, I don't have a lot of time to add things to the package if it does not directly relate to the internal app so I'm limited in that respect.

I have updated the project tab and currently there are two open issues that you could work on.
1. https://github.com/werner-scholtz/kalender/issues/79 
2. https://github.com/werner-scholtz/kalender/issues/86 

If you want to chat just let me know, and we can organise something.
